sudo: 'required'

services:
  - docker

before_script:
  - cd provision/files/control/src/dolibarr
  - make pull

script:
  - ls -al
  - docker build -t dolibarr:latest .
  # - make build

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PWD ;
      make push ;
    fi

notifications:
  email: false
