---
version: "3.3"
services:
  dolibarr:
    container_name: dolibarr
    image: dolibarr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - dolibarr_conf:/var/www/dolibarr/htdocs/conf
      - dolibarr_docs:/var/www/dolibarr/htdocs/documents
    networks:
      - dolibarr-network

  db:
    container_name: db
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - dolibarr-network

networks:
  dolibarr-network:

volumes:
  mariadb:
  dolibarr_conf:
  dolibarr_docs:
